export let timelineElements = [
  {
    id: 1,
    title: "First time meeting",
    date: "January 19th",
    buttonText: "View",
    image: require("../images/first-met.jpg"),
    description: "i love you",
  },
  {
    id: 2,
    title: "During Fiji",
    date: "January 26th",
    buttonText: "View",
    image: require("../images/fiji-film.JPG"),
    description: null,
  },
  {
    id: 3,
    title: "Leaving Fiji",
    date: "February 3rd",
    buttonText: "View",
    image: require("../images/leaving-fiji.JPG"),
    description: null,
  },
  {
    id: 4,
    title: "Valentines day",
    date: "February 14th",
    buttonText: "View",
    image: require("../images/hospital.jpg"),
    description: null,
  },
  {
    id: 5,
    title: "Getting to know you",
    date: "Mid February",
    buttonText: "View",
    image: require("../images/first-selfie.JPG"),
    description: null,
  },
  {
    id: 6,
    title: "Boat cruise night",
    date: "March 14th",
    buttonText: "View",
    image: require("../images/boat-cruise.jpg"),
    description: null,
  },
  {
    id: 7,
    title: "When you became my girlfriend",
    date: "March 20th",
    buttonText: "View",
    image: require("../images/selfie-4.jpg"),
    description: null,
  },
  {
    id: 8,
    title: "Our surf trips",
    date: "March-April",
    buttonText: "View",
    image: require("../images/selfie-1.JPG"),
    description: null,
  },
  {
    id: 9,
    title: "THE night out",
    date: "April 25",
    buttonText: "View",
    image: require("../images/night-out-1.jpg"),
    description: null,
  },
  {
    id: 10,
    title: "The other photo... (I had to)",
    date: "April 25",
    buttonText: "View",
    image: require("../images/night-out-2.jpg"),
    description: null,
  },
  {
    id: 11,
    title: "Studying with you",
    date: "April-May",
    buttonText: "View",
    image: require("../images/sleeping-fleur.jpg"),
    description: null,
  },
  {
    id: 12,
    title: "Dandenong Ranges",
    date: "May 25th",
    buttonText: "View",
    image: require("../images/ranges-1.jpg"),
    description: null,
  },
  {
    id: 13,
    title: "Leaving for thailand",
    date: "June 16th",
    buttonText: "View",
    image: require("../images/sleeping-fleur-2.jpg"),
    description: null,
  },
  {
    id: 14,
    title: "While I was away",
    date: "June-July",
    buttonText: "View",
    image: require("../images/facetime.PNG"),
    description: null,
  },
  {
    id: 15,
    title: "Coming home",
    date: "July 17th",
    buttonText: "View",
    image: require("../images/hospital-selfie.jpg"),
    description: null,
  },
  {
    id: 16,
    title: "Getting out of hospital",
    date: "July 20th",
    buttonText: "View",
    image: require("../images/out-of-hospital.jpg"),
    description: null,
  },
  {
    id: 17,
    title: "Still in honeymoon...",
    date: "Now",
    buttonText: "View",
    image: require("../images/selfie-5.jpg"),
    description: "krkrkkr",
  },
];
